capsule-generator.cc File Reference
capsule-generator.cc File Reference
CLI capsule generator.
#include <iostream>
#include <string>
#include <boost/program_options.hpp>
#include <roboptim/capsule/fitter.hh>
#include <roboptim/capsule/util.hh>
Functions
int main (int argc, char **argv)
Detailed Description
CLI capsule generator.
Function Documentation
int main (int argc, char ** argv)
References roboptim::capsule::Fitter::computeBestFitCapsule(), roboptim::capsule::computeBoundingCapsulePolyhedron(), roboptim::capsule::computeConvexPolyhedron(), roboptim::capsule::convertCapsuleToSolverParam(), roboptim::capsule::Fitter::initParam(), and roboptim::capsule::Fitter::solutionParam().