roboptim::capsule::Fitter Class Reference
roboptim::capsule::Fitter Class Reference
Capsule fitter class.
#include <roboptim/capsule/fitter.hh>
Public Member Functions
Fitter (const polyhedrons_t &polyhedrons, std::string solver="ipopt") throw ()
Constructor.
~Fitter () throw ()
const polyhedrons_t polyhedrons () const throw ()
Get polyhedron attribute.
void polyhedrons (const polyhedrons_t &polyhedrons) throw ()
Set polyhedron attribute.
value_type initVolume () const throw ()
Get capsule volume for initial parameters.
value_type solutionVolume () const throw ()
Get capsule volume for solution parameters.
const argument_t initParam () const throw ()
Get initial capsule parameters.
const argument_t solutionParam () const throw ()
Get solution capsule parameters.
void computeBestFitCapsule (const argument_t &initParam) throw ()
Compute best fitting capsule over polyhedron.
void computeBestFitCapsule (const polyhedrons_t &polyhedrons, const argument_t &initParam) throw ()
Compute best fitting capsule over polyhedron vector.
const argument_t computeBestFitCapsuleParam (const argument_t &initParam) throw ()
Compute best fitting capsule over polyhedron vector.
const argument_t computeBestFitCapsuleParam (const polyhedrons_t &polyhedrons, const argument_t &initParam) throw ()
Compute best fitting capsule over polyhedron.
Protected Member Functions
void impl_computeBestFitCapsuleParam (const polyhedrons_t &polyhedrons, const argument_t &initParam, argument_t &solutionParam) throw ()
Implementation of best fitting capsule computation.
Detailed Description
Capsule fitter class.
This class computes the best fitting capsule over a polyhedron.
Constructor & Destructor Documentation
roboptim::capsule::Fitter::Fitter (const polyhedrons_t & polyhedrons, std::string solver = "ipopt") throw ()
Constructor.
roboptim::capsule::Fitter::~Fitter () throw ()
Member Function Documentation
void roboptim::capsule::Fitter::computeBestFitCapsule (const argument_t & initParam) throw ()
Compute best fitting capsule over polyhedron.
Polyhedron vector attribute is used to compute capsule and set capsuleParam attribute.
Parameters
initParam initial capsule parameters
Referenced by main().
void roboptim::capsule::Fitter::computeBestFitCapsule (const polyhedrons_t & polyhedrons, const argument_t & initParam) throw ()
Compute best fitting capsule over polyhedron vector.
Parameters
polyhedron Polyhedron over which the capsule is fitted
initParam initial capsule parameters
const argument_t roboptim::capsule::Fitter::computeBestFitCapsuleParam (const argument_t & initParam) throw ()
Compute best fitting capsule over polyhedron vector.
Polyhedron vector attribute is used to compute capsule and set capsuleParam attribute.
Parameters
initParam initial capsule parameters
Returns
capsule parameters
const argument_t roboptim::capsule::Fitter::computeBestFitCapsuleParam (const polyhedrons_t & polyhedrons, const argument_t & initParam) throw ()
Compute best fitting capsule over polyhedron.
Parameters
polyhedrons Polyhedron vector over which the capsule is fitted
initParam initial capsule parameters
Returns
capsule parameters
void roboptim::capsule::Fitter::impl_computeBestFitCapsuleParam (const polyhedrons_t & polyhedrons, const argument_t & initParam, argument_t & solutionParam) throw () protected
Implementation of best fitting capsule computation.
Parameters
polyhedrons Polyhedron vector over which the capsule is fitted
initParam initial capsule parameters
Returns
solutionParam solution capsule parameters
const argument_t roboptim::capsule::Fitter::initParam () const throw ()
Get initial capsule parameters.
Referenced by main(), and roboptim::capsule::operator<<().
value_type roboptim::capsule::Fitter::initVolume () const throw ()
Get capsule volume for initial parameters.
Referenced by roboptim::capsule::operator<<().
const polyhedrons_t roboptim::capsule::Fitter::polyhedrons () const throw ()
Get polyhedron attribute.
void roboptim::capsule::Fitter::polyhedrons (const polyhedrons_t & polyhedrons) throw ()
Set polyhedron attribute.
const argument_t roboptim::capsule::Fitter::solutionParam () const throw ()
Get solution capsule parameters.
Referenced by main(), and roboptim::capsule::operator<<().
value_type roboptim::capsule::Fitter::solutionVolume () const throw ()
Get capsule volume for solution parameters.
Referenced by roboptim::capsule::operator<<().